parameters:
    strata.preview_mode.data_provider:

services:
    # Twig extension
    Strata\Symfony\Twig\TwigExtension:
        tags: [ 'twig.extension' ]

    Strata\Symfony\EventSubscriber\TwigEventSubscriber:
        tags: [ 'kernel.event_subscriber' ]

    # Preview mode
    Strata\Symfony\EventSubscriber\PreviewModeEventSubscriber:
        tags: [ 'kernel.event_subscriber' ]

    # Data collector for web debug toolbar
    Strata\Symfony\DataCollector\StrataDataCollector:
        tags:
            -
                name: data_collector
                id: 'strata'